prompt
prompt INSERTING into DFP_ENTROPY
prompt =========================
prompt
SET DEFINE OFF;

Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('AUD_CODECS_ID',null,1.1073,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('BROWSER_LANG_ID',10,0.8447,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('BROWSER_NAME_ID',null,2.1878,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('CANVAS_FP',10.8,2.496,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('CONNECTION_TYPE',2.8,0.7116,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('CONTENT_ENCODING_ID',null,0.7172,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('CONTENT_LANG_ID',10,2.4296,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('COOKIES_ENABLED',0.4,0.0335,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('CPU_ARCH_ID',null,2.775,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('DISP_COLOR_DEPTH',null,0.8789,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('DISP_SCREEN_RES_RATIO',null,0.7025,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('DO_NOT_TRACK',null,0.6194,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('HAS_LIED_BROWSER',null,0.0913,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('HAS_LIED_LANGS',null,0.5671,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('HAS_LIED_OS',null,0.0427,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('HTTP_HEAD_ACCEPT_ID',null,1.1493,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('IP_ADDRESS',null,4.4241,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('IP_ADDRESS_OCTET',null,1.0954,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('OS_FONTS_ID',13.9,3.5283,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('PLATFORM_ID',null,1.298,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('PLUGINS',15.4,3.3082,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('TIMEZONE',3.04,0.6955,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('TOUCH_SUP',null,0.7025,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('USER_AGENT_BROWSER_ID',0,1.3601,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('USER_AGENT_DEVICE_ID',0,0.2793,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('USER_AGENT_ENGINE_ID',13,0.9973,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('USER_AGENT_OS_ID',3,1.1712,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('USE_OF_LOCAL_STORAGE',null,0.3427,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('USE_OF_SESS_STORAGE',null,0.3103,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('VID_CODECS_ID',null,2.0869,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('WEBGL_VENDOR_RENDERER_ID',null,3.2538,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('WEBRTC_FP',null,0.5671,sysdate,sysdate);
Insert into DFP_ENTROPY (COLUMN_NAME,PRE_COMPUTED_ENTROPY,CALCULATED_ENTROPY,INSERT_DT,UPDATE_DT) values ('INDEXED_DB',null,0,sysdate,sysdate);

commit;
