prompt ============================================
prompt INSERTING into DFP_ATTRIB_MAP
prompt ============================================

SET DEFINE OFF;

Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (1,1,'USER_AGENT_OS','userAgentOS','User Agent - OS','OS and version of client machine','chrome|firefox|opera|safari|ie',1,1,'USER_AGENT_OS_ID');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (2,2,'USER_AGENT_BROWSER','userAgentBrowser','User Agent - Browser','Name and version of client browser','chrome|firefox|opera|safari|ie',1,0,'USER_AGENT_BROWSER_ID');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (3,3,'USER_AGENT_ENGINE','userAgentEngine','User Agent - Engine','Web browser engine and version','chrome|firefox|opera|safari|ie',1,0,'USER_AGENT_ENGINE_ID');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (4,4,'USER_AGENT_DEVICE','userAgentDevice','User Agent - Device','Type and model of client device','chrome|firefox|opera|safari|ie',1,0,'USER_AGENT_DEVICE_ID');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (7,5,'DISP_COLOR_DEPTH','displayColorDepth','Color Depth','Number of bits used to indicate the color of a single pixel. Its also known as bit depth','chrome|firefox|opera|safari|ie',1,1,'DISP_COLOR_DEPTH');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (8,6,'DISP_SCREEN_RES_RATIO','displayScreenResolutionRatio','Screen Resolution Ratio','Ratio of the width to the height of a screen.','chrome|firefox|opera|safari|ie',1,1,'DISP_SCREEN_RES_RATIO');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (19,7,'CPU_ARCH','cpuArchitecture','CPU Architecture','CPU processor in client machine','chrome|firefox|opera|safari|ie',1,0,'CPU_ARCH_ID');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (15,8,'CANVAS_FP','canvas','Canvas','A base 64 encoded value of HTML5 <canvas> element which is used to draw graphics. It is recommended to hash the output prior to using due to length.','chrome|firefox|opera|safari|ie',1,1,'CANVAS_FP');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (30,9,'HTTP_HEAD_ACCEPT','accept','Accept','HTTP header sent to the server that contains information regarding the type of media that are acceptable for the response','chrome|firefox|opera|safari|ie',1,0,'HTTP_HEAD_ACCEPT_ID');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (31,10,'CONTENT_ENCODING','acceptEncoding','Accept Encoding','HTTP header sent to the server that lists the compression methods supported by the browser','chrome|firefox|opera|safari|ie',1,0,'CONTENT_ENCODING_ID');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (32,11,'CONTENT_LANG','acceptLanguage','Accept Language','HTTP header sent to the server that indicates the preferred languages for the response','chrome|firefox|opera|safari|ie',1,0,'CONTENT_LANG_ID');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (28,12,'IP_ADDRESS','ipAddress','IP Address','User local/public IP address','chrome|firefox|opera|safari|ie',1,0,'IP_ADDRESS');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (29,13,'IP_ADDRESS_OCTET','ipAddressOctet','IP Address Octet','User local/public IP address first two values','chrome|firefox|opera|safari|ie',1,1,'IP_ADDRESS_OCTET');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (13,14,'OS_FONTS','fonts','OS Fonts','List of fonts installed in client browser','chrome|firefox|opera|safari|ie',1,0,'OS_FONTS_ID');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (14,15,'BROWSER_LANG','language','Langugae','Primary language of client browser','chrome|firefox|opera|safari|ie',1,1,'BROWSER_LANG_ID');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (9,16,'TIMEZONE','timezone','Timezone','Time difference between UTC time and local time, in minutes.UTC time is the same as GMT time.','chrome|firefox|opera|safari|ie',1,1,'TIMEZONE');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (18,17,'PLATFORM','navigatorPlatform','Platform','Platform of the client browser','chrome|firefox|opera|safari|ie',1,0,'PLATFORM_ID');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (10,18,'PLUGINS','plugins','Plugins','List of installed plugins in client browser','chrome|firefox|opera|safari|ie',1,1,'PLUGINS');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (23,19,'USE_OF_LOCAL_STORAGE','localStorage','Local Storage','Local storage is available in browser','chrome|firefox|opera|safari|ie',1,0,'USE_OF_LOCAL_STORAGE');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (22,20,'USE_OF_SESS_STORAGE','sessionStorage','Session Storage','Session storage is available in browser','chrome|firefox|opera|safari|ie',1,0,'USE_OF_SESS_STORAGE');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (20,21,'DO_NOT_TRACK','doNotTrack','Do Not Track','Do Not Track is enabled in client browser','chrome|firefox|opera|safari|ie',1,0,'DO_NOT_TRACK');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (25,22,'HAS_LIED_LANGS','hasLiedLanguages','Lied Language','Language version of browser is equal to the first language of user''s prefernce langage. If yes then value will be true else false.','chrome|firefox|opera|safari|ie',1,0,'HAS_LIED_LANGS');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (26,23,'HAS_LIED_OS','hasLiedOs','Lied OS','Browser OS changes then it return true else value will be false.','chrome|firefox|opera|safari|ie',1,0,'HAS_LIED_OS');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (27,24,'HAS_LIED_BROWSER','hasLiedBrowser','Lied Browser','Identify is browser is running in stimulated mode or not.','chrome|firefox|opera|safari|ie',1,0,'HAS_LIED_BROWSER');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (12,25,'WEBGL_VENDOR_RENDERER','webGL','Web GL','Name of the WebGL Renderer and Vendor.','chrome|firefox|opera|safari|ie',1,0,'WEBGL_VENDOR_RENDERER_ID');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (21,26,'COOKIES_ENABLED','cookie','Cookie','cookies are enabled in client browser','chrome|firefox|opera|safari|ie',1,0,'COOKIES_ENABLED');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (16,27,'TOUCH_SUP','touch','Touch Support','Touch support available in client device','chrome|firefox|opera|safari|ie',1,0,'TOUCH_SUP');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (17,28,'CONNECTION_TYPE','connection','Connection','Cellular and WIFI connection information that the client''s device (i.e. Android devices) is utilizin','chrome|firefox|opera|safari|ie',1,0,'CONNECTION_TYPE');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (11,29,'WEBRTC_FP','webRTCSupport','Web RTC Support','Real Time Communications(RTC) capabilities supported by browser','chrome|firefox|opera|safari|ie',1,0,'WEBRTC_FP');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (5,30,'VID_CODECS','videoCodecAvailable','Video Codec','List of video codecs supported by client browser','chrome|firefox|opera|safari|ie',1,0,'VID_CODECS_ID');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (6,31,'AUD_CODECS','audioCodecAvailable','Audio Codec','List of audio codecs supported by client browser','chrome|firefox|opera|safari|ie',1,0,'AUD_CODECS_ID');
Insert into DFP_ATTRIB_MAP (COLUMN_ID,ATTRIB_ID,COLUMN_NAME,ATTRIB_NAME,ATTRIB_DISP_NAME,ATTRIB_DESC,BROWSER_SUPP,ACTIVE_FLAG,PASS_APP_FLAG,PAD_COLUMN_NAME) values (24,32,'INDEXED_DB','indexedDb','Indexed DB','Indexed DB is avaiable in browser','chrome|firefox|opera|safari|ie',1,0,'INDEXED_DB');


commit;

prompt
prompt Done.
