REM INSERTING into DFP_SCHEMA1.DIM_CONTENT_ENCODING
SET DEFINE OFF;
Insert into DFP_SCHEMA1.DIM_CONTENT_ENCODING (CONTENT_ENCODING_ID,CONTENT_ENCODING,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (2,'GZIP,DEFLATE,BR',null,null,null);
Insert into DFP_SCHEMA1.DIM_CONTENT_ENCODING (CONTENT_ENCODING_ID,CONTENT_ENCODING,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (3,'GZIP,DEFLATE,SDCH',null,null,null);
Insert into DFP_SCHEMA1.DIM_CONTENT_ENCODING (CONTENT_ENCODING_ID,CONTENT_ENCODING,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (4,'GZIP, DEFLATE',null,null,null);
Insert into DFP_SCHEMA1.DIM_CONTENT_ENCODING (CONTENT_ENCODING_ID,CONTENT_ENCODING,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (5,'GZIP, DEFLATE, LZMA',null,null,null);
Insert into DFP_SCHEMA1.DIM_CONTENT_ENCODING (CONTENT_ENCODING_ID,CONTENT_ENCODING,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (6,'GZIP,DEFLATE',null,null,null);
Insert into DFP_SCHEMA1.DIM_CONTENT_ENCODING (CONTENT_ENCODING_ID,CONTENT_ENCODING,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (7,'GZIP, DEFLATE, BR',null,null,null);
Insert into DFP_SCHEMA1.DIM_CONTENT_ENCODING (CONTENT_ENCODING_ID,CONTENT_ENCODING,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (-1,'-1',null,null,null);
