REM INSERTING into DFP_SCHEMA1.DIM_BROWSER_LANG
SET DEFINE OFF;
Insert into DFP_SCHEMA1.DIM_BROWSER_LANG (BROWSER_LANG_ID,BROWSER_LANG,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (1,'EN-US',null,null,null);
Insert into DFP_SCHEMA1.DIM_BROWSER_LANG (BROWSER_LANG_ID,BROWSER_LANG,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (3,'LANG=EN-US|SYSLANG=|USERLANG=',null,null,null);
Insert into DFP_SCHEMA1.DIM_BROWSER_LANG (BROWSER_LANG_ID,BROWSER_LANG,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (4,'EN-IN',null,null,null);
Insert into DFP_SCHEMA1.DIM_BROWSER_LANG (BROWSER_LANG_ID,BROWSER_LANG,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (5,'EN-GB',null,null,null);
Insert into DFP_SCHEMA1.DIM_BROWSER_LANG (BROWSER_LANG_ID,BROWSER_LANG,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (-1,'-1',null,null,null);
