REM INSERTING into DFP_SCHEMA1.DIM_PLATFORM
SET DEFINE OFF;
Insert into DFP_SCHEMA1.DIM_PLATFORM (PLATFORM_ID,PLATFORM,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (2,'LINUX X86_64',null,null,null);
Insert into DFP_SCHEMA1.DIM_PLATFORM (PLATFORM_ID,PLATFORM,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (3,'LINUX ARMV8L',null,null,null);
Insert into DFP_SCHEMA1.DIM_PLATFORM (PLATFORM_ID,PLATFORM,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (4,'IPHONE',null,null,null);
Insert into DFP_SCHEMA1.DIM_PLATFORM (PLATFORM_ID,PLATFORM,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (5,'LINUX ARMV7L',null,null,null);
Insert into DFP_SCHEMA1.DIM_PLATFORM (PLATFORM_ID,PLATFORM,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (6,'LINUX I686',null,null,null);
Insert into DFP_SCHEMA1.DIM_PLATFORM (PLATFORM_ID,PLATFORM,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (7,'WIN32',null,null,null);
Insert into DFP_SCHEMA1.DIM_PLATFORM (PLATFORM_ID,PLATFORM,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (8,'LINUX AARCH64',null,null,null);
Insert into DFP_SCHEMA1.DIM_PLATFORM (PLATFORM_ID,PLATFORM,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (-1,'-1',null,null,null);
