prompt
prompt INSERTING into DFP_PQ_CONFIG
prompt ============================
prompt

SET DEFINE OFF;

Insert into DFP_PQ_CONFIG (JB_THREAD_ID,CF_PASS_NUMBER,CF_ATTRIB_ID,CF_MATCH_DEGREE,CF_SUB_PASS_NUMBER) values (1,1,13,'S',1);
Insert into DFP_PQ_CONFIG (JB_THREAD_ID,CF_PASS_NUMBER,CF_ATTRIB_ID,CF_MATCH_DEGREE,CF_SUB_PASS_NUMBER) values (1,1,16,'S',2);
Insert into DFP_PQ_CONFIG (JB_THREAD_ID,CF_PASS_NUMBER,CF_ATTRIB_ID,CF_MATCH_DEGREE,CF_SUB_PASS_NUMBER) values (1,1,8,'S',3);

Insert into DFP_PQ_CONFIG (JB_THREAD_ID,CF_PASS_NUMBER,CF_ATTRIB_ID,CF_MATCH_DEGREE,CF_SUB_PASS_NUMBER) values (1,2,13,'S',1);
Insert into DFP_PQ_CONFIG (JB_THREAD_ID,CF_PASS_NUMBER,CF_ATTRIB_ID,CF_MATCH_DEGREE,CF_SUB_PASS_NUMBER) values (1,2,16,'S',2);
Insert into DFP_PQ_CONFIG (JB_THREAD_ID,CF_PASS_NUMBER,CF_ATTRIB_ID,CF_MATCH_DEGREE,CF_SUB_PASS_NUMBER) values (1,2,1,'S',3);
Insert into DFP_PQ_CONFIG (JB_THREAD_ID,CF_PASS_NUMBER,CF_ATTRIB_ID,CF_MATCH_DEGREE,CF_SUB_PASS_NUMBER) values (1,2,5,'S',4);
Insert into DFP_PQ_CONFIG (JB_THREAD_ID,CF_PASS_NUMBER,CF_ATTRIB_ID,CF_MATCH_DEGREE,CF_SUB_PASS_NUMBER) values (1,2,6,'S',5);

Insert into DFP_PQ_CONFIG (JB_THREAD_ID,CF_PASS_NUMBER,CF_ATTRIB_ID,CF_MATCH_DEGREE,CF_SUB_PASS_NUMBER) values (1,3,8,'S',1);
Insert into DFP_PQ_CONFIG (JB_THREAD_ID,CF_PASS_NUMBER,CF_ATTRIB_ID,CF_MATCH_DEGREE,CF_SUB_PASS_NUMBER) values (1,3,1,'S',2);
Insert into DFP_PQ_CONFIG (JB_THREAD_ID,CF_PASS_NUMBER,CF_ATTRIB_ID,CF_MATCH_DEGREE,CF_SUB_PASS_NUMBER) values (1,3,5,'S',3);
Insert into DFP_PQ_CONFIG (JB_THREAD_ID,CF_PASS_NUMBER,CF_ATTRIB_ID,CF_MATCH_DEGREE,CF_SUB_PASS_NUMBER) values (1,3,6,'S',4);
Insert into DFP_PQ_CONFIG (JB_THREAD_ID,CF_PASS_NUMBER,CF_ATTRIB_ID,CF_MATCH_DEGREE,CF_SUB_PASS_NUMBER) values (1,3,18,'S',5);
Insert into DFP_PQ_CONFIG (JB_THREAD_ID,CF_PASS_NUMBER,CF_ATTRIB_ID,CF_MATCH_DEGREE,CF_SUB_PASS_NUMBER) values (1,3,15,'S',6);



commit;

prompt
prompt Done.
