REM INSERTING into DFP_SCHEMA1.DIM_CPU_ARCH
SET DEFINE OFF;
Insert into DFP_SCHEMA1.DIM_CPU_ARCH (CPU_ARCH_ID,CPU_ARCH,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (-1,'-1',null,null,null);
Insert into DFP_SCHEMA1.DIM_CPU_ARCH (CPU_ARCH_ID,CPU_ARCH,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (1,'AMD64',null,null,null);
