REM INSERTING into DFP_SCHEMA1.DIM_HTTP_HEAD_ACCEPT
SET DEFINE OFF;
Insert into DFP_SCHEMA1.DIM_HTTP_HEAD_ACCEPT (HTTP_HEAD_ACCEPT_ID,HTTP_HEAD_ACCEPT,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (2,'TEXT/HTML,APPLICATION/XHTML+XML,APPLICATION/XML;Q=0.9,*/*;Q=0.8',null,null,null);
Insert into DFP_SCHEMA1.DIM_HTTP_HEAD_ACCEPT (HTTP_HEAD_ACCEPT_ID,HTTP_HEAD_ACCEPT,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (3,'*/*',null,null,null);
Insert into DFP_SCHEMA1.DIM_HTTP_HEAD_ACCEPT (HTTP_HEAD_ACCEPT_ID,HTTP_HEAD_ACCEPT,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (4,'APPLICATION/XML',null,null,null);
Insert into DFP_SCHEMA1.DIM_HTTP_HEAD_ACCEPT (HTTP_HEAD_ACCEPT_ID,HTTP_HEAD_ACCEPT,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (5,'IMAGE/WEBP,*/*',null,null,null);
Insert into DFP_SCHEMA1.DIM_HTTP_HEAD_ACCEPT (HTTP_HEAD_ACCEPT_ID,HTTP_HEAD_ACCEPT,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (6,'APPLICATION/JSON',null,null,null);
Insert into DFP_SCHEMA1.DIM_HTTP_HEAD_ACCEPT (HTTP_HEAD_ACCEPT_ID,HTTP_HEAD_ACCEPT,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (-1,'-1',null,null,null);
