REM INSERTING into DFP_SCHEMA1.DIM_AUD_CODECS
SET DEFINE OFF;
Insert into DFP_SCHEMA1.DIM_AUD_CODECS (AUD_CODECS_ID,AUD_CODECS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (2,'APPLICATION/VND.APPLE.MPEGURL|APPLICATION/X-MPEGURL|AUDIO/MP4; CODECS="MP4A.40.2"|AUDIO/MP4; CODECS="MP4A.40.5"|AUDIO/MP4; CODECS="MP4A.67"',null,null,null);
Insert into DFP_SCHEMA1.DIM_AUD_CODECS (AUD_CODECS_ID,AUD_CODECS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (3,'AUDIO/MP4; CODECS="MP4A.40.2"|AUDIO/MP4; CODECS="MP4A.40.5"|AUDIO/MP4; CODECS="MP4A.67"|AUDIO/WEBM; CODECS="VORBIS"',null,null,null);
Insert into DFP_SCHEMA1.DIM_AUD_CODECS (AUD_CODECS_ID,AUD_CODECS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (4,'AUDIO/MP4; CODECS="MP4A.40.2"|AUDIO/MP4; CODECS="MP4A.40.5"|AUDIO/MP4; CODECS="MP4A.67"',null,null,null);
Insert into DFP_SCHEMA1.DIM_AUD_CODECS (AUD_CODECS_ID,AUD_CODECS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (5,'APPLICATION/VND.APPLE.MPEGURL|AUDIO/MP4; CODECS="MP4A.40.2"|AUDIO/MP4; CODECS="MP4A.40.5"|AUDIO/MP4; CODECS="MP4A.67"|AUDIO/WEBM; CODECS="VORBIS"',null,null,null);
Insert into DFP_SCHEMA1.DIM_AUD_CODECS (AUD_CODECS_ID,AUD_CODECS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (6,'AUDIO/WEBM; CODECS="VORBIS"',null,null,null);
Insert into DFP_SCHEMA1.DIM_AUD_CODECS (AUD_CODECS_ID,AUD_CODECS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (7,'AUDIO/MP4; CODECS="MP4A.40.2"|AUDIO/MP4; CODECS="MP4A.40.5"|AUDIO/WEBM; CODECS="VORBIS"',null,null,null);
Insert into DFP_SCHEMA1.DIM_AUD_CODECS (AUD_CODECS_ID,AUD_CODECS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (8,'AUDIO/MP4; CODECS="MP4A.40.5"',null,null,null);
Insert into DFP_SCHEMA1.DIM_AUD_CODECS (AUD_CODECS_ID,AUD_CODECS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (-1,'-1',null,null,null);
