REM INSERTING into DFP_SCHEMA1.DIM_USER_AGENT_DEVICE
SET DEFINE OFF;
Insert into DFP_SCHEMA1.DIM_USER_AGENT_DEVICE (USER_AGENT_DEVICE_ID,USER_AGENT_DEVICE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (2,'IPHONE|MOBILE|APPLE',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_DEVICE (USER_AGENT_DEVICE_ID,USER_AGENT_DEVICE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (3,'XPERIA PHONE|MOBILE|SONY',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_DEVICE (USER_AGENT_DEVICE_ID,USER_AGENT_DEVICE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (4,'XT1650|MOBILE|MOTOROLA',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_DEVICE (USER_AGENT_DEVICE_ID,USER_AGENT_DEVICE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (5,'O|MOBILE|MOTOROLA',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_DEVICE (USER_AGENT_DEVICE_ID,USER_AGENT_DEVICE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (6,'MI 3S|MOBILE|XIAOMI',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_DEVICE (USER_AGENT_DEVICE_ID,USER_AGENT_DEVICE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (7,'OG3|MOBILE|MOTOROLA',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_DEVICE (USER_AGENT_DEVICE_ID,USER_AGENT_DEVICE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (8,'SM-G7102|MOBILE|SAMSUNG',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_DEVICE (USER_AGENT_DEVICE_ID,USER_AGENT_DEVICE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (9,'NEXUS 5|MOBILE|LG',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_DEVICE (USER_AGENT_DEVICE_ID,USER_AGENT_DEVICE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (10,'NEXUS 6|MOBILE|MOTOROLA',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_DEVICE (USER_AGENT_DEVICE_ID,USER_AGENT_DEVICE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (-1,'-1',null,null,null);
