REM INSERTING into DFP_SCHEMA1.DIM_USER_AGENT_OS
SET DEFINE OFF;
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (-1,'-1',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (1,'ANDROID|7.0',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (3,'ANDROID|7.1.9',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (4,'LINUX',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (5,'ANDROID|6.0.1',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (6,'IOS|10.0.2',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (7,'MAC OS|10.10.4',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (8,'ANDROID|4.2.1',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (9,'ANDROID|4.4.2',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (10,'ANDROID|7.0.9',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (11,'ANDROID|4.3',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (12,'ANDROID|7.0.1',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (13,'IOS|10.1.1',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (14,'WINDOWS|7',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (15,'FEDORA',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_OS (USER_AGENT_OS_ID,USER_AGENT_OS,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (16,'LINUX|X86_64',null,null,null);
