REM INSERTING into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE
SET DEFINE OFF;
Insert into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE (USER_AGENT_ENGINE_ID,USER_AGENT_ENGINE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (2,'WEBKIT|600.7.12',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE (USER_AGENT_ENGINE_ID,USER_AGENT_ENGINE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (3,'GECKO|45.0',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE (USER_AGENT_ENGINE_ID,USER_AGENT_ENGINE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (4,'GECKO|19.0',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE (USER_AGENT_ENGINE_ID,USER_AGENT_ENGINE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (5,'WEBKIT|534.30',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE (USER_AGENT_ENGINE_ID,USER_AGENT_ENGINE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (6,'WEBKIT|535.19',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE (USER_AGENT_ENGINE_ID,USER_AGENT_ENGINE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (7,'WEBKIT|537.36',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE (USER_AGENT_ENGINE_ID,USER_AGENT_ENGINE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (8,'WEBKIT|538.15',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE (USER_AGENT_ENGINE_ID,USER_AGENT_ENGINE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (9,'WEBKIT|602.2.14',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE (USER_AGENT_ENGINE_ID,USER_AGENT_ENGINE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (10,'TRIDENT|7.0',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE (USER_AGENT_ENGINE_ID,USER_AGENT_ENGINE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (11,'GECKO|44.0',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE (USER_AGENT_ENGINE_ID,USER_AGENT_ENGINE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (12,'GECKO|49.0',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE (USER_AGENT_ENGINE_ID,USER_AGENT_ENGINE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (13,'WEBKIT|602.1.50',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE (USER_AGENT_ENGINE_ID,USER_AGENT_ENGINE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (14,'WEBKIT|534.57.2',null,null,null);
Insert into DFP_SCHEMA1.DIM_USER_AGENT_ENGINE (USER_AGENT_ENGINE_ID,USER_AGENT_ENGINE,EFF_FROM_DT,EFF_TO_DT,UPDATE_DT) values (-1,'-1',null,null,null);
