prompt
prompt Creating table DFP_API_LOG
prompt ============================
prompt

declare
	lv_tbl exception;
	pragma exception_init(lv_tbl,-00942);
	lv_part_name	varchar2(100);
begin
	begin
		execute immediate 'drop table DFP_API_LOG purge';
	exception
		when lv_tbl then
			null;
	end;

	execute immediate 'create table DFP_API_LOG (
							MASTER_DEVICE_ID	VARCHAR2(100 CHAR),
							REF_NUM				VARCHAR2(100 CHAR),
							SESSION_ID			VARCHAR2(100 CHAR),
							REQ_START_TS		TIMESTAMP,
							REQ_END_TS			TIMESTAMP,
							REQ_TOT_TIME		VARCHAR2(300) generated always as (extract(hour from (REQ_END_TS-REQ_START_TS))||'' hours and ''||extract(minute from (REQ_END_TS-REQ_START_TS))||'' minute and ''||extract(second from (REQ_END_TS-REQ_START_TS))||'' seconds.''),
							ATTRIB_PASS_CNT		NUMBER,
							STATUS_CD			NUMBER(5),
							STATUS_MSG			VARCHAR2(2000 CHAR)
						)
						tablespace #TBS_DFP_DATA
						pctfree 10
						initrans 1
						maxtrans 255
						nologging
						storage (
							initial 64K
							next 256K
							minextents 1
							maxextents unlimited
							pctincrease 0
						)';
	
	execute immediate 'comment on column DFP_API_LOG.MASTER_DEVICE_ID is ''Master Device Id.''';
	execute immediate 'comment on column DFP_API_LOG.REF_NUM is ''TimeStamp( As unique Identifier).''';
	execute immediate 'comment on column DFP_API_LOG.SESSION_ID is ''Generated by Java.''';
	execute immediate 'comment on column DFP_API_LOG.REQ_START_TS is ''Req Start Timestamp (systimestamp).''';
	execute immediate 'comment on column DFP_API_LOG.REQ_END_TS is ''Req End Timestamp (systimestamp).''';
	execute immediate 'comment on column DFP_API_LOG.REQ_TOT_TIME is ''Request Total Time.''';
	execute immediate 'comment on column DFP_API_LOG.ATTRIB_PASS_CNT is ''Number of atrrbutes passed.''';
	execute immediate 'comment on column DFP_API_LOG.STATUS_CD is ''status code.''';
	execute immediate 'comment on column DFP_API_LOG.STATUS_MSG is ''Status Message.''';
end;
/


prompt
prompt Done.
