prompt
prompt Creating table DFP_LOG
prompt ============================
prompt

declare
	lv_tbl exception;
	pragma exception_init(lv_tbl,-00942);
	lv_part_name	varchar2(100);
begin
	begin
		execute immediate 'drop table DFP_LOG purge';
	exception
		when lv_tbl then
			null;
	end;

	execute immediate 'create table DFP_LOG (
							MASTER_DEVICE_ID			VARCHAR2(100 CHAR),
							REF_NUM						VARCHAR2(100 CHAR),
							SESSION_ID					VARCHAR2(100 CHAR),
							REQ_TS						TIMESTAMP,
							TOT_TIME					NUMBER,
							DIM_ID_TIME					NUMBER,
							IDX_TIME					NUMBER,
							PQ_TOT_TIME					NUMBER,
							PQ_PASS_TIME				VARCHAR2(100 CHAR),
							PQ_MATCH_CNT				NUMBER,
							FQ_EVAL_CNT					NUMBER,
							FQ_MATCH_CNT				NUMBER,
							FQ_TOT_TIME					NUMBER,
							FQ_EVAL_TIME				VARCHAR2(4000 CHAR),
							FQ_ENTROPY_FETCH_TIME		NUMBER,
							FQ_RSLT_LOAD_TIME			NUMBER,
							REQ_LOAD_TIME				NUMBER,
							PAD_LOAD_TIME				NUMBER,
							STATUS_CD					NUMBER(5),
							STATUS_MSG					VARCHAR2(2000 CHAR)
						)
						tablespace #TBS_DFP_DATA
						pctfree 10
						initrans 1
						maxtrans 255
						nologging
						storage (
							initial 64K
							next 256K
							minextents 1
							maxextents unlimited
							pctincrease 0
						)';
	
	execute immediate 'comment on column DFP_LOG.MASTER_DEVICE_ID is ''Master Device Id.''';
	execute immediate 'comment on column DFP_LOG.REF_NUM is ''Session_id +TimeStamp( As unique Identifier).''';
	execute immediate 'comment on column DFP_LOG.SESSION_ID is ''Generated by Java.''';
	execute immediate 'comment on column DFP_LOG.REQ_TS is ''Timestamp (systimestamp).''';
	execute immediate 'comment on column DFP_LOG.TOT_TIME is ''Total Time in centiseconds.''';
	execute immediate 'comment on column DFP_LOG.DIM_ID_TIME is ''Time to fetch the Dimention id in centiseconds.''';
	execute immediate 'comment on column DFP_LOG.IDX_TIME is ''Time to index the DFP request in centiseconds.''';
	execute immediate 'comment on column DFP_LOG.PQ_TOT_TIME is ''Time taken in PQ stage in centiseconds.''';
	execute immediate 'comment on column DFP_LOG.PQ_PASS_TIME is ''Time taken in PQ Pass execution stage in centiseconds.''';
	execute immediate 'comment on column DFP_LOG.PQ_MATCH_CNT is ''Match counts at PQ stage.''';
	execute immediate 'comment on column DFP_LOG.FQ_EVAL_CNT is ''PQ counts considered for final matchings.''';
	execute immediate 'comment on column DFP_LOG.FQ_MATCH_CNT is ''Final match counts.''';
	execute immediate 'comment on column DFP_LOG.FQ_TOT_TIME is ''FQ stage time in centiseconds.''';
	execute immediate 'comment on column DFP_LOG.FQ_EVAL_TIME is ''Break up of final-qualification in centiseconds.''';
	execute immediate 'comment on column DFP_LOG.FQ_ENTROPY_FETCH_TIME is ''Time in centiseconds taken to load entropy into collection.''';
	execute immediate 'comment on column DFP_LOG.FQ_RSLT_LOAD_TIME is ''Time in centiseconds taken to load the FQ Result table.''';
	execute immediate 'comment on column DFP_LOG.REQ_LOAD_TIME is ''Time in centiseconds taken to load the Request table.''';
	execute immediate 'comment on column DFP_LOG.PAD_LOAD_TIME is ''Time in centiseconds taken to load the PAD table.''';
	execute immediate 'comment on column DFP_LOG.STATUS_CD is ''Status code i.e. 0-Success/1-Failure due to DB Error/2-Failure due to timeout.''';
	execute immediate 'comment on column DFP_LOG.STATUS_MSG is ''Status Message.''';
end;
/


prompt
prompt Done.
