--TODO: Commented below for temporary fix, fix to ensure proper
--grants available to the corresponding app user for the schema
--on which it is being installed (not #APP_USERNAME = wrong tag).
--grant select on db_version to #APP_USERNAME;
--grant select on jobs to #APP_USERNAME;
--grant select, insert, update, delete on job_log to #APP_USERNAME;
--grant select on partition_settings to #APP_USERNAME;
--grant select on pg_purger_config to #APP_USERNAME;
--grant select on pg_purger_log to #APP_USERNAME;
--grant select, insert, update, delete on sm_reports to #APP_USERNAME;
--grant select, insert, update, delete on sm_report_sections to #APP_USERNAME;