connect SYS/"#SYS_PASSWORD" as SYSDBA
set echo on
spool #SOURCE_PATH/instance_12c/pdb/log/create_pdb.log
CREATE PLUGGABLE DATABASE #PDB_DATABASE_NAME   
ADMIN USER #PDB_USER_NAME IDENTIFIED BY #PDB_USER_PWD  
storage (maxsize #PDB_MAX_SIZE MAX_SHARED_TEMP_SIZE #PDB_MAX_SHARED_TEMP_SIZE)  
DEFAULT TABLESPACE #DEFAULT_TABLESPACE DATAFILE '#INSTALL_BASE/data001/#PDB_DATABASE_NAME/#PDB_DATABASE_NAME_#DEFAULT_TABLESPACE.dbf' SIZE 5M REUSE AUTOEXTEND ON   
file_name_convert=(
'#INSTALL_BASE/data001/#DB_CONTAINER_SEED_NAME/#SYSTEM_TABLESPACE.dbf','#INSTALL_BASE/data001/#PDB_DATABASE_NAME/#SYSTEM_TABLESPACE.dbf',
'#INSTALL_BASE/data001/#DB_CONTAINER_SEED_NAME/#SYSAUX_TABLESPACE.dbf','#INSTALL_BASE/data001/#PDB_DATABASE_NAME/#SYSAUX_TABLESPACE.dbf',
'#INSTALL_BASE/data001/#DB_CONTAINER_SEED_NAME/#TEMP_TABLESPACE.dbf','#INSTALL_BASE/data001/#PDB_DATABASE_NAME/#TEMP_TABLESPACE.dbf');

alter pluggable database #PDB_DATABASE_NAME open;

spool off
exit;
